export default [
  {
    id: 1,
    type: "Reflex Plus Adult Cat Food Salmon White",
    tags: [
      { title: "Product", value: "Dog Food" },
      { title: "Size", value: "385gm" },
    ],
    price: 140000,
    image: "product-1.png",
    promo: "Free Toys & Free Shaker",
  },
  {
    id: 2,
    type: "Reflex Plus Adult Cat Food Salmon Yellow",
    tags: [
      { title: "Product", value: "Cat Food" },
      { title: "Size", value: "1.5kg" },
    ],
    price: 165000,
    image: "product-2.png",
    promo: "Free Toys & Free Shaker",
  },
  {
    id: 3,
    type: "Cat scratching ball toy kitten sisal rope ball",
    tags: [{ title: "Product", value: "Toy" }],
    price: 1100000,
    image: "product-3.png",
    promo: "Free Cat Food",
  },
  {
    id: 4,
    type: "Cute Pet Cat Warm Nest",
    tags: [{ title: "Product", value: "Toy" }],
    price: 410000,
    image: "product-4.png",
    promo: "Free Cat Food",
  },
  {
    id: 5,
    type: "NaturVet Dogs - Omega-Gold Plus Salmon Oil",
    tags: [
      { title: "Product", value: "Dog Food" },
      { title: "Size", value: "385gm" },
    ],
    price: 350000,
    image: "product-5.png",
    promo: "Free Toys & Free Shaker",
  },
  {
    id: 6,
    type: "Costumes Fashion Pet Clother Cowboy Rider",
    tags: [
      { title: "Product", value: "Dog Food" },
      { title: "Size", value: "1.5kg" },
    ],
    price: 500000,
    image: "product-6.png",
    promo: "Free Toys & Free Shaker",
  },
  {
    id: 7,
    type: "Costumes Chicken Drumsti ck Headband",
    tags: [{ title: "Product", value: "Costume" }],
    price: 400000,
    image: "product-7.png",
    promo: "Free Cat Food",
  },
  {
    id: 8,
    type: "Plush Pet Toy",
    tags: [{ title: "Product", value: "Toy" }],
    price: 250000,
    image: "product-8.png",
    promo: "Free Food & Shaker",
  },
];
